##
# This is a YAML representation of the Solr schema required by the application.
# Solr::update_schema() will read this file and update Solr via its REST API.
#
# Schema summary:
#
# metadata_*_txtim                    arbitrary metadata elements
# *_facet                             faceted versions of the metadata elements
# Item::SolrFields                    fields used by the application
# Collection::SolrFields              fields used by the application
#
# There are no classic fields, only dynamicFields and copyFields.
#
# Dynamic fields have the following naming scheme:
#
# *_{type}
# *_{type}i: indexed
# *_{type}m: multiValued
# *_{type}im: indexed, multiValued
#

#########################################################################
# FIELD TYPES
#########################################################################

fieldTypes:
    # Natural/human sort field whose goal is to sort pretty much like Finder
    # or Explorer would sort files.
  - name: 'text_en_natural'
    class: 'solr.TextField'
    autoGeneratePhraseQueries: 'true'
    positionIncrementGap: '100'
    analyzer:
      tokenizer:
        # KeywordTokenizer does no actual tokenizing, so the entire input
        # string is preserved as a single token.
        class: 'solr.KeywordTokenizerFactory'
      filters:
        - class: 'solr.LowerCaseFilterFactory'
        - class: 'solr.TrimFilterFactory'
          # Remove leading articles
        - class: 'solr.PatternReplaceFilterFactory'
          pattern: "^(a |the |les |la |le |l'|de la |du |des )"
          replacement:
          replace: 'all'
          # Left-pad numbers with zeroes
        - class: 'solr.PatternReplaceFilterFactory'
          pattern: '(\d+)'
          replacement: '00000$1'
          replace: 'all'
          # Left-trim zeroes to produce 6 digit numbers
        - class: 'solr.PatternReplaceFilterFactory'
          pattern: '0*([0-9]{6,})'
          replacement: '$1'
          replace: 'all'

#########################################################################
# COPY FIELDS
#########################################################################

copyFields:
  - source: 'collection_si'
    dest: 'collection_si_facet'
  - source: 'id'
    dest: 'searchall_natsort_en_im'
  - source: 'external_id_si'
    dest: 'searchall_natsort_en_im'
  - source: 'metadata_*'
    dest: 'searchall_natsort_en_im'
  - source: 'metadata_*'
    dest: '*_facet'

#########################################################################
# DYNAMIC FIELDS
#########################################################################

dynamicFields:
    ################# facet fields ##################
  - name: '*_facet'
    type: string
    stored: true
    indexed: true
    multiValued: true
    docValues: true

    ################# integer fields ##################
  - name: '*_i'
    type: int
    stored: true
    indexed: false
    multiValued: false
  - name: '*_ii'
    type: int
    stored: true
    indexed: true
    multiValued: false
  - name: '*_im'
    type: int
    stored: true
    indexed: false
    multiValued: true
  - name: '*_iim'
    type: int
    stored: true
    indexed: true
    multiValued: true
  - name: '*_l'
    type: long
    stored: true
    indexed: true
  - name: '*_li'
    type: long
    stored: true
    indexed: true
    multiValued: false
  - name: '*_lm'
    type: long
    stored: true
    indexed: false
    multiValued: true
  - name: '*_lim'
    type: long
    stored: true
    indexed: true
    multiValued: true

    ################# float fields ##################
  - name: '*_f'
    type: float
    stored: true
    indexed: false
  - name: '*_fi'
    type: float
    stored: true
    indexed: true
    multiValued: false
  - name: '*_fm'
    type: float
    stored: true
    indexed: false
    multiValued: true
  - name: '*_fim'
    type: float
    stored: true
    indexed: true
    multiValued: true
  - name: '*_d'
    type: double
    stored: true
    indexed: false
    multiValued: false
  - name: '*_di'
    type: double
    stored: true
    indexed: true
    multiValued: false
  - name: '*_dm'
    type: double
    stored: true
    indexed: false
    multiValued: true
  - name: '*_dim'
    type: double
    stored: true
    indexed: true
    multiValued: true

    ################# string fields ##################
  - name: '*_s'
    type: string
    stored: true
    indexed: false
    multiValued: false
  - name: '*_si'
    type: string
    stored: true
    indexed: true
    multiValued: false
  - name: '*_sm'
    type: string
    stored: true
    indexed: false
    multiValued: true
  - name: '*_sim'
    type: string
    stored: true
    indexed: true
    multiValued: true

    ################# text fields ##################
  - name: '*_natsort_en_i'
    type: text_en_natural
    stored: true
    indexed: true
    multiValued: false
  - name: '*_natsort_en_im'
    type: text_en_natural
    stored: true
    indexed: true
    multiValued: true
  - name: '*_txt'
    type: text_general
    stored: true
    indexed: false
    multiValued: false
  - name: '*_txti'
    type: text_general
    stored: true
    indexed: true
    multiValued: false
  - name: '*_txtm'
    type: text_general
    stored: true
    indexed: false
    multiValued: true
  - name: '*_txtim'
    type: text_general
    stored: true
    indexed: true
    multiValued: true

    ################# boolean fields ##################
  - name: '*_b'
    type: boolean
    stored: true
    indexed: false
  - name: '*_bi'
    type: boolean
    stored: true
    indexed: true
    multiValued: false
  - name: '*_bm'
    type: boolean
    stored: true
    indexed: false
    multiValued: true
  - name: '*_bim'
    type: boolean
    stored: true
    indexed: true
    multiValued: true

    ################# date fields ##################
  - name: '*_dt'
    type: date
    indexed: true
    stored: true
  - name: '*_dti'
    type: date
    indexed: true
    stored: true
    multiValued: false
  - name: '*_dtm'
    type: date
    indexed: false
    stored: true
    multiValued: true
  - name: '*_dtim'
    type: date
    indexed: true
    stored: true
    multiValued: true

  # Type used to index the lat and lon components for the "location" FieldType
  - name: '*_coordinate'
    type: tdouble
    indexed: true
    stored: false

  - name: '*_loc'
    type: location
    indexed: true
    stored: true
  # some trie-coded dynamic fields for faster range queries
  - name: '*_ti'
    type: tint
    indexed: true
    stored: true
  - name: '*_tl'
    type: tlong
    indexed: true
    stored: true
  - name: '*_tf'
    type: tfloat
    indexed: true
    stored: true
  - name: '*_td'
    type: tdouble
    indexed: true
    stored: true
  - name: '*_tdt'
    type: tdate
    indexed: true
    stored: true
  - name: '*_c'
    type: currency
    indexed: true
    stored: true
  - name: 'ignored_*'
    type: ignored
    multiValued: true
  - name: 'attr_*'
    type: text_general
    indexed: true
    stored: true
    multiValued: true
  - name: 'random_*'
    type: random
