development: &development
  # Pathname of the Medusa root on the NCSA condo mount.
  :repository_pathname: /repo
  # URL of the IIIF Image API 2.1 endpoint.
  :iiif_url: http://localhost:8182/iiif/2
  # Cantaloupe-specific.
  :image_server_api_endpoint: http://localhost:8182
  :image_server_api_user: admin
  :image_server_api_secret: secret
  :medusa_url: https://medusa.library.illinois.edu/
  :medusa_user:
  :medusa_secret:
  :elasticsearch_endpoint: http://localhost:9200
  :downloader_url: http://download.library.illinois.edu:8080
  :downloader_user:
  :downloader_password:

test:
  :repository_pathname: /repo
  :iiif_url: http://localhost:8182/iiif/2
  :image_server_api_endpoint: http://localhost:8182
  :image_server_api_user: admin
  :image_server_api_secret: secret
  :medusa_url: https://medusa.library.illinois.edu/
  :medusa_user: machine_user
  :medusa_secret: FoifWowdeth3
  :elasticsearch_endpoint: http://localhost:9200
  :downloader_url: http://download.library.illinois.edu:8080
  :downloader_user:
  :downloader_password:

production: &production
  :repository_pathname: /repo
  :iiif_url: http://localhost:8182/iiif/2
  :image_server_api_endpoint: http://localhost:8182
  :image_server_api_user: admin
  :image_server_api_secret: secret
  :medusa_url: https://medusa.library.illinois.edu/
  :medusa_user: machine_user
  :medusa_secret: FoifWowdeth3
  :elasticsearch_endpoint: http://localhost:9200
  :downloader_url: http://download.library.illinois.edu:8080
  :downloader_user:
  :downloader_password:
