development: &development
  # Region in which all AWS actions will be performed.
  :aws_region:

  # Credentials for an AWS account with read/write access to the application-
  # specific S3 bucket below.
  :dls_aws_access_key_id:
  :dls_aws_secret_key:

  # Application-specific S3 bucket.
  :dls_s3_bucket:

  # Base URI of an Elasticsearch server.
  :elasticsearch_endpoint:         http://localhost:9200

  # IIIF Image API 2.1 endpoint.
  :iiif_url:                       http://localhost:8182/iiif/2

  # Base URI of a Cantaloupe image server service.
  :image_server_api_endpoint:      http://localhost:8182

  # Credentials for accessing the Cantaloupe HTTP API via HTTP Basic.
  :image_server_api_user:
  :image_server_api_secret:

  # Base URI of Medusa.
  :medusa_url:                     https://medusa.library.illinois.edu/

  # Medusa API credentials.
  :medusa_user:
  :medusa_secret:

  # Name of the Medusa repository bucket.
  :medusa_s3_bucket:

  # Credentials for an AWS account with read-only access to the bucket above.
  :medusa_s3_bucket_access_key_id:
  :medusa_s3_bucket_secret_key:

  # Base URI of the Medusa Downloader.
  :downloader_url:                 http://download.library.illinois.edu:8080

  # Medusa Downloader credentials.
  :downloader_user:
  :downloader_password:

test:
  <<: *development

production: &production
  :aws_region:
  :dls_aws_access_key_id:
  :dls_aws_secret_key:
  :dls_s3_bucket:
  :elasticsearch_endpoint:
  :iiif_url:
  :image_server_api_endpoint:
  :image_server_api_user:
  :image_server_api_secret:
  :medusa_url:                     https://medusa.library.illinois.edu/
  :medusa_user:
  :medusa_secret:
  :medusa_s3_bucket:
  :medusa_s3_bucket_access_key_id:
  :medusa_s3_bucket_secret_key:
  :downloader_url:                 http://download.library.illinois.edu:8080
  :downloader_user:
  :downloader_password:
