development: &development
  :repository_pathname: /repo
  :iiif_url: http://localhost:8182/iiif
  :solr_url: http://localhost:8983/solr/
  :solr_core: peartree
  :solr_default_facetable_fields:
    - subject_txti
  :solr_id_field: id
  :solr_class_field: class_si
  :solr_default_search_field: searchall_txtim
  :solr_more_like_this_endpoint: /mlt

test:
  :repository_pathname: /repo
  :iiif_url: http://localhost:8182/iiif
  :solr_url: http://localhost:8983/solr/
  :solr_core: peartree
  :solr_default_facetable_fields:
    - subject_txti
  :solr_id_field: id
  :solr_class_field: class_si
  :solr_default_search_field: searchall_txtim
  :solr_more_like_this_endpoint: /mlt

production: &production
  :repository_pathname: /repo
  :iiif_url: http://localhost:8182/iiif
  :solr_url: http://localhost:8983/solr/
  :solr_core: peartree
  :solr_default_facetable_fields:
    - subject_txti
  :solr_id_field: id
  :solr_class_field: class_si
  :solr_default_search_field: searchall_txtim
  :solr_more_like_this_endpoint: /mlt
