development: &development
  :repository_pathname: /repo
  :iiif_url: http://localhost:8182/iiif/2
  :image_server_api_endpoint: http://localhost:8182
  :image_server_api_user: admin
  :image_server_api_secret: secret
  :medusa_url: https://medusa.library.illinois.edu/
  :medusa_user: machine_user
  :medusa_secret: FoifWowdeth3
  :medusa_cache_ttl: 2592000
  :api_user: api_user
  :api_secret: secret
  :api_ips:
    - 127.0.
  :solr_url: http://localhost:8983/solr/
  :solr_core: peartree
  :solr_default_facetable_fields:
    - subject_txti
  :solr_id_field: id
  :solr_class_field: class_si
  :solr_default_search_field: searchall_natsort_en_im
  :solr_more_like_this_endpoint: /mlt

test:
  :repository_pathname: /repo
  :iiif_url: http://localhost:8182/iiif/2
  :image_server_api_endpoint: http://localhost:8182
  :image_server_api_user: admin
  :image_server_api_secret: secret
  :medusa_url: https://medusa.library.illinois.edu/
  :medusa_user: machine_user
  :medusa_secret: FoifWowdeth3
  :medusa_cache_ttl: 0
  :api_user: api_user
  :api_secret: secret
  :api_ips:
    - 127.0.
  :solr_url: http://localhost:8983/solr/
  :solr_core: peartree
  :solr_default_facetable_fields:
    - subject_txti
  :solr_id_field: id
  :solr_class_field: class_si
  :solr_default_search_field: searchall_natsort_en_im
  :solr_more_like_this_endpoint: /mlt

production: &production
  :repository_pathname: /repo
  :iiif_url: http://localhost:8182/iiif/2
  :image_server_api_endpoint: http://localhost:8182
  :image_server_api_user: admin
  :image_server_api_secret: secret
  :medusa_url: https://medusa.library.illinois.edu/
  :medusa_user: machine_user
  :medusa_secret: FoifWowdeth3
  :medusa_cache_ttl: 2592000
  :api_user: api_user
  :api_secret: secret
  :api_ips: # https://answers.uillinois.edu/illinois/page.php?id=47572
    - 127.0.
    - 128.174.
    - 130.126.
    - 192.17.
    - 72.36.64.
    - 2620:0:e00:
    - 172.16.
    - 10.192.
  :solr_url: http://localhost:8983/solr/
  :solr_core: peartree
  :solr_default_facetable_fields:
    - subject_txti
  :solr_id_field: id
  :solr_class_field: class_si
  :solr_default_search_field: searchall_natsort_en_im
  :solr_more_like_this_endpoint: /mlt
