development: &development
  # Pathname of the Medusa root on the NCSA condo mount.
  :repository_pathname: /repo
  # URL of the IIIF Image API 2.1 endpoint.
  :iiif_url: http://localhost:8182/iiif/2
  # Cantaloupe-specific.
  :image_server_api_endpoint: http://localhost:8182
  :image_server_api_user: admin
  :image_server_api_secret: secret
  :medusa_url: https://medusa.library.illinois.edu/
  :medusa_user:
  :medusa_secret:
  # User authorized to use the REST API, at /api.
  :api_user: api_user
  :api_secret: secret
  # Client IP addresses allowed to access the REST API.
  :api_ips:
    - 127.0.
  :elasticsearch_endpoint: http://localhost:9200
  :downloader:
    :url: http://download.library.illinois.edu:8080
    :user:
    :password:

test:
  :repository_pathname: /repo
  :iiif_url: http://localhost:8182/iiif/2
  :image_server_api_endpoint: http://localhost:8182
  :image_server_api_user: admin
  :image_server_api_secret: secret
  :medusa_url: https://medusa.library.illinois.edu/
  :medusa_user: machine_user
  :medusa_secret: FoifWowdeth3
  :api_user: api_user
  :api_secret: secret
  :api_ips:
    - 127.0.
  :elasticsearch_endpoint: http://localhost:9200
  :downloader:
    :url: http://download.library.illinois.edu:8080
    :user:
    :password:

production: &production
  :repository_pathname: /repo
  :iiif_url: http://localhost:8182/iiif/2
  :image_server_api_endpoint: http://localhost:8182
  :image_server_api_user: admin
  :image_server_api_secret: secret
  :medusa_url: https://medusa.library.illinois.edu/
  :medusa_user: machine_user
  :medusa_secret: FoifWowdeth3
  :api_user: api_user
  :api_secret: secret
  :api_ips: # https://answers.uillinois.edu/illinois/page.php?id=47572
    - 127.0.
    - 128.174.
    - 130.126.
    - 192.17.
    - 72.36.64.
    - 2620:0:e00:
    - 172.16.
    - 10.192.
  :elasticsearch_endpoint: http://localhost:9200
  :downloader:
    :url: http://download.library.illinois.edu:8080
    :user:
    :password:
